export enum AccionAuditoria {
  // Autenticación
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  REGISTRO = 'REGISTRO',
  CAMBIO_CONTRASENA = 'CAMBIO_CONTRASENA',
  RECUPERAR_CONTRASENA = 'RECUPERAR_CONTRASENA',

  // CRUD General
  CREAR = 'CREAR',
  ACTUALIZAR = 'ACTUALIZAR',
  ELIMINAR = 'ELIMINAR',
  ACTIVAR = 'ACTIVAR',
  DESACTIVAR = 'DESACTIVAR',

  // Acciones Específicas
  PAGO_REGISTRADO = 'PAGO_REGISTRADO',
  PAGO_ABONO = 'PAGO_ABONO',
  CONTRATO_FINALIZADO = 'CONTRATO_FINALIZADO',
  CONTRATO_VENCIDO = 'CONTRATO_VENCIDO',
  CONSULTA_REPORTES = 'CONSULTA_REPORTES',
  EXPORTAR_DATOS = 'EXPORTAR_DATOS',
}
